### ISSUE TITLE
[Issue]PScredential error running Test-ProxyLogon.ps1

### ISSUE THREAD

**Issue by Andy-Houghton1** [microsoft/CSS-Exchange#140] opened 2021-03-08 11:38 UTC
**Describe the issue**
I am running Test_proxyLogon.ps1 against Exchange 2010 and receive the error shown in the script output below. I have tried it for the local Exchange server and against all servers with the same results. 

**Expected behavior**
I am expecting the script to run and provide the output report

**Script Output**
Unable to find type [pscredential]: make sure that the assembly containing this type is loaded
At E:\Test-ProxyLogon.ps1:84 char:27
+             [pscredential] <<<<
    + CategoryInfo          : InvalidOperation: (pscredential:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Additional context**
It is running under an account with domain admin and organizational management rights for Exchange. The powershell version is version 2.

**Comment by live-motion** [comment] 2021-03-08 11:48
same error on Exchange 2010, powershell 2.0
Unable to find type [pscredential]: make sure that the assembly containing this type is loaded.
At D:\Downloads\Test-ProxyLogon.ps1:79 char:27
+             [pscredential] <<<<
    + CategoryInfo          : InvalidOperation: (pscredential:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by rbgtk** [comment] 2021-03-08 12:25
Same as issue #108

**Comment by bill-long** [comment] 2021-03-08 14:09
Yeah, duplicate of #108 . We'll continue to use that issue for discussion and any updates around this.

**Closed by bill-long** 2021-03-08 14:09 UTC
Labels: Issue
