### ISSUE TITLE
No baseline for 15.0.516.30

### ISSUE THREAD

**Issue by ronnessim** [microsoft/CSS-Exchange#245] opened 2021-03-10 18:25 UTC
[PS] >.\CompareExchangeHashes.ps1
[03/10/2021 13:21:14] Started...
Found exchange version: 15.0.1497.2
Loaded baseline for 15.0.1497.2, hashes number 7395
Loaded baseline for 15.0.1497.12, hashes number 7464
Can't find local baseline for 15.0.516.30
Downloading baseline file from GitHub to C:\<PATH>\baseline_15.0.516.30.zip
LoadFromGitHub : C:\<PATH>\baseline_15.0.516.30.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\<PATH>\CompareExchangeHashes.ps1:613 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -in ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

Checked in the repo, and there is a file for 15.0.516.32 but not .30.

**Comment by L0g333** [comment] 2021-03-10 18:28
There is already a issue for that missing baseline. See #222

**Comment by irrgit** [comment] 2021-03-10 18:30
Same thing happened to me. 
Note that I am running the script from C:\Users\<myusername>\Dwonloads folder, if that matters.

`[03/10/2021 13:26:21] Started...
Found exchange version: 15.0.1497.2
Loaded baseline for 15.0.1473.5, hashes number 7464
Loaded baseline for 15.0.1178.4, hashes number 7452
Loaded baseline for 15.0.1497.12, hashes number 7464
Loaded baseline for 15.0.1365.7, hashes number 7463
Loaded baseline for 15.0.1473.3, hashes number 7394
Loaded baseline for 15.0.1395.4, hashes number 7395
Loaded baseline for 15.0.1365.1, hashes number 7462
Loaded baseline for 15.0.1497.0, hashes number 7464
Can't find local baseline for 15.0.516.30
Downloading baseline file from GitHub to C:\Users\<myusername>\Downloads\baseline_15.0.516.30.zip`

**Comment by bill-long** [comment] 2021-03-10 18:36
Closing as duplicate of #222

**Closed by bill-long** 2021-03-10 18:36 UTC
