### ISSUE TITLE
[Issue] - Health Checker - Credential Guard Detection

### ISSUE THREAD

**Issue by reuvygroovy** [microsoft/CSS-Exchange#2079] opened 2024-05-01 14:48 UTC
**Provide Version Number**
Exchange Health Checker v23.11.29.1401
Exchange 2019, Windows 2022

**Describe the issue**
Incorrect detection of Credential Guard

**Expected behavior**
Credential Guard is disabled on these servers and you should two detections (not sure why two) where one is enabled and the other shows it's not enabled

See here two screenshots which are from the same report which contradict on another
![image](https://github.com/microsoft/CSS-Exchange/assets/1325158/e420add5-3dc4-4942-a765-0db82dd971c3)
![image](https://github.com/microsoft/CSS-Exchange/assets/1325158/f5ddde11-eb79-4994-a939-938e6870ee14)

**Comment by dpaulson45** [comment] 2024-05-01 14:54
@reuvygroovy `Credential Guard Enabled` is only going to show up once in the HTML report **per server**. It appears that you have one server that is determined to be enabled, where the second is determined to be disabled.

**Comment by reuvygroovy** [comment] 2024-05-01 15:16
Thanks, I see that. It is confusing and should appear a bit more clearly. Anyhow, when running on a bunch of servers simultaneously it shows that Cred Guard is enabled, but then I ran individually on one server and I see that it is disabled. Seems like there is a bug.

**Comment by dpaulson45** [comment] 2024-05-01 15:29
@reuvygroovy How are you running it to make it seem like Cred Guard is enabled? How are you running it against one server where it seems like it is disabled? Does it show enabled when running remotely from a particular server? 

I need an instance where you are seeing Server X showing enabled when running Health Checker in scenario 1, and in scenario 2 for Server X showing it as disabled. 

If you can, provide screen shots and the data output from the Health Checker and email it to ExToolsFeedback@microsoft.com

**Comment by dpaulson45** [comment] 2024-05-08 18:10
Closing as once we got the data, the issue appeared to be caused by old Health Checker.

**Closed by dpaulson45** 2024-05-08 18:10 UTC
Labels: Health Checker, Awaiting feedback

**Comment by SaschaTrollGeberit** [comment] 2024-08-13 09:18
After upgrade to Windows Server 2022 the healthchecker seems to get the wrong info and informs that Credential Guard is active, but when I check its not active (False)
[PS] C:\WINDOWS\system32>'CredentialGuard’ -match ((Get-ComputerInfo).DeviceGuardSecurityServicesConfigured)
False
[PS] C:\WINDOWS\system32>$null -ne ($osInformation.CredentialGuardCimInstance | Where-Object { $_ -eq 1 })
False

Healthchecker versions 24.08.08.1523

**Comment by dpaulson45** [comment] 2024-08-13 13:55
@SaschaTrollGeberit please email in the data, xml and txt file to ExToolsFeedback@microsoft.com

**Comment by SaschaTrollGeberit** [comment] 2024-08-15 08:43
> @SaschaTrollGeberit please email in the data, xml and txt file to [ExToolsFeedback@microsoft.com](mailto:ExToolsFeedback@microsoft.com)

Sorry, my bad. Unsuppoted enviromnent, we switched back. Credential Guard was running. Script was OK.
Thanks!
