### ISSUE TITLE
[Issue] HealthChecker - Exception when DisabledComponents is set to 0xffffffff

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#536] opened 2021-04-26 15:46 UTC
**Describe the issue**
Customers reported the following issue:

```
Exception setting "IPv6DisabledComponents": "Cannot convert value "0xffffffff" to type "System.Double". Error: "Input 
string was not in a correct format.""
At C:\Temp\HealthChecker.ps1:2947 char:5
+     $osInformation.NetworkInformation.IPv6DisabledComponents = Invoke ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
at Get-OperatingSystemInformation, C:\Temp\HealthChecker.ps1: line 2947
at Get-HealthCheckerExchangeServer, C:\Temp\HealthChecker.ps1: line 2787
at Main, C:\Temp\HealthChecker.ps1: line 5615
at <ScriptBlock>, C:\Temp\HealthChecker.ps1: line 5655
at <ScriptBlock>, <No file>: line 1
```

This can be caused when `DisabledComponents` is set to `0xffffffff` which is `-1`.  We don't recommend to set this value as it can cause a system startup delay:

_Additionally, system startup will be delayed for five seconds if IPv6 is disabled by incorrectly, setting the DisabledComponents registry setting to a value of 0xffffffff. The correct value should be 0xff. For more information, see Internet Protocol Version 6 (IPv6) Overview._

**Expected behavior**
We should not run into an exception. We should instead display a warning that the current value may cause issues.

**Script Output**
```
Exception setting "IPv6DisabledComponents": "Cannot convert value "0xffffffff" to type "System.Double". Error: "Input 
string was not in a correct format.""
At C:\Temp\HealthChecker.ps1:2947 char:5
+     $osInformation.NetworkInformation.IPv6DisabledComponents = Invoke ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
at Get-OperatingSystemInformation, C:\Temp\HealthChecker.ps1: line 2947
at Get-HealthCheckerExchangeServer, C:\Temp\HealthChecker.ps1: line 2787
at Main, C:\Temp\HealthChecker.ps1: line 5615
at <ScriptBlock>, C:\Temp\HealthChecker.ps1: line 5655
at <ScriptBlock>, <No file>: line 1
```

**Additional context**
More information about the problematic value: https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/configure-ipv6-in-windows#use-registry-key-to-configure-ipv6

Migrated From: https://github.com/dpaulson45/HealthChecker/issues/533

**Comment by lusassl-msft** [comment] 2021-04-29 15:10
Will take care of this issue.

**Comment by lusassl-msft** [comment] 2021-04-30 16:18
The issue was caused by a wrong data type (`String` Value). The correct data type for this value is `DWORD`. The script works fine if the correct data type is used. However, I'll add another check to show a warning in case the `DisableComponents DWORD` is set to `0xffffffff (-1)` which may cause some issues (system startup delay).

**Comment by dpaulson45** [comment] 2021-05-03 20:25
@lusassl-msft did you just see that in your lab or in someone's environment? Do you think we need to check for this if it isn't set to `DWORD`?

**Comment by lusassl-msft** [comment] 2021-05-04 09:10
I've tried to reproduce the issue with the correct value type `DWORD` (as documented) but was not able to do so. I then checked the customer report again and noticed that they used the wrong value type `String`. 
That was the only issue report from a customer in this regard.
A long-term solution would be to optimize the `Invoke-RegistryGetValue` function by adding an optional parameter `ValueType` which then can be used to check for the requested value type via `RegistryKey.GetValueKind(String) Method` and only return a matching result. 
What do you think?

**Comment by dpaulson45** [comment] 2021-05-04 14:15
Long term solution would be to improve `Get-RemoteRegistryValue` in the Shared location, as that is where we are going to be moving the extern files to and have them be that style.

**Comment by lusassl-msft** [comment] 2021-05-04 15:01
Okay, let's close this issue and file a work item for the `Get-RemoteRegistryValue` work.

**Closed** 2021-05-12 07:41 UTC
Labels: Health Checker, Issue
