### ISSUE TITLE
Baseline 15.0.995.28 missing

### ISSUE THREAD

**Issue by TuXHuNT3R** [microsoft/CSS-Exchange#351] opened 2021-03-15 12:03 UTC
Hi guys

I've tried to run the script "CompareExchangeHashes.ps1" and I get an error, that baseline_15.0.995.28 is not found. In the folder with the extracted baselines, i have the folder 15.0.995.29, but noch the folder 15.0.995.28. Here's my powershell output:

[03/15/2021 12:55:59] Started...
Found exchange version: 15.0.1497.2
Can't find local baseline for 15.0.1178.4
Downloading baseline file from GitHub to C:\temp\hafnium_test_Script_Logs\baseline_15.0.1178.4.zip
Loaded baseline for 15.0.1178.4, hashes number 7452
Can't find local baseline for 15.0.1076.9
Downloading baseline file from GitHub to C:\temp\hafnium_test_Script_Logs\baseline_15.0.1076.9.zip
Loaded baseline for 15.0.1076.9, hashes number 7353
Can't find local baseline for 15.0.1497.12
Downloading baseline file from GitHub to C:\temp\hafnium_test_Script_Logs\baseline_15.0.1497.12.zip
Loaded baseline for 15.0.1497.12, hashes number 7464
Can't find local baseline for 15.0.1473.3
Downloading baseline file from GitHub to C:\temp\hafnium_test_Script_Logs\baseline_15.0.1473.3.zip
Loaded baseline for 15.0.1473.3, hashes number 7394
Can't find local baseline for 15.0.1497.8
Downloading baseline file from GitHub to C:\temp\hafnium_test_Script_Logs\baseline_15.0.1497.8.zip
Loaded baseline for 15.0.1497.8, hashes number 7464
Can't find local baseline for 15.0.1320.4
Downloading baseline file from GitHub to C:\temp\hafnium_test_Script_Logs\baseline_15.0.1320.4.zip
Loaded baseline for 15.0.1320.4, hashes number 7463
Can't find local baseline for 15.0.995.29
Downloading baseline file from GitHub to C:\temp\hafnium_test_Script_Logs\baseline_15.0.995.29.zip
Loaded baseline for 15.0.995.29, hashes number 11830
Can't find local baseline for 15.0.1497.0
Downloading baseline file from GitHub to C:\temp\hafnium_test_Script_Logs\baseline_15.0.1497.0.zip
Loaded baseline for 15.0.1497.0, hashes number 7464
Can't find local baseline for 15.0.995.28
Downloading baseline file from GitHub to C:\temp\hafnium_test_Script_Logs\baseline_15.0.995.28.zip
LoadFromGitHub : C:\temp\hafnium_test_Script_Logs\baseline_15.0.995.28.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
In C:\temp\hafnium_test_Script_Logs\CompareExchangeHashes.ps1:660 Zeichen:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

I think it's a typo somewhere in the script. Can you upload a fixed script? Thank you

**Comment by bill-long** [comment] 2021-03-15 14:35
Duplicate of #313 . This one is already on the list of missing baselines.

**Closed by bill-long** 2021-03-15 14:35 UTC
