### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by microtechs** [microsoft/CSS-Exchange#268] opened 2021-03-11 02:28 UTC
**Describe the issue**
Attempted to run CompareExchangeHashes.ps1

**Expected behavior**
Comparison of Exchange hashes

**Script Output**
Found exchange version: 15.1.2176.2
Can't find local baseline for 15.1.1591.8
Downloading baseline file from GitHub to C:\Users\UserName\Desktop\baseline_15.1.1591.8.zip
LoadFromGitHub : C:\Users\UserName\Desktop\baseline_15.1.1591.8.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\Users\UserName\Desktop\CompareExchangeHashes.ps1:636 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Additional context**
I ran it inside of powershell as administrator

**Comment by tivrobo** [comment] 2021-03-11 02:39
same here;

```
PS C:\Admin> c:\admin\CompareExchangeHashes.ps1
[03/10/2021 21:19:28] Started...
Found exchange version: 15.1.2176.2
Can't find local baseline for 15.1.1591.8
Downloading baseline file from GitHub to C:\Admin\baseline_15.1.1591.8.zip
LoadFromGitHub : C:\Admin\baseline_15.1.1591.8.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\admin\CompareExchangeHashes.ps1:618 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub
```

It seems that there is no baseline for this version exists in this repo...
So to fix that, I'm just create a fake baseline_15.1.1591.8.zip file...

**Comment by bill-long** [comment] 2021-03-11 02:49
Closing as duplicate of #265

**Closed by bill-long** 2021-03-11 02:49 UTC
Labels: Issue
