### ISSUE TITLE
[Issue] SourceSideValidations - 

### ISSUE THREAD

**Issue by copsec00** [microsoft/CSS-Exchange#1960] opened 2024-01-28 17:47 UTC
**Describe the issue**
When I run the powershell script, it does not complete. It fails after Started executing job Get-Statistics. Connecting via a remote computer via powershell still shows the same error. Specifying the $Server variable as FQDN or just hostname results in the same error.

**Expected behavior**

**Script Output**
Added job Get-IpmSubtree to queue.
Added job Get-NonIpmSubtree to queue.
Added job Get-Statistics to queue.
Started executing job Get-IpmSubtree.
Started executing job Get-NonIpmSubtree.
Started executing job Get-Statistics.
Cannot bind parameter 'ConnectionUri'. Cannot convert value "http:///powershell" to type "System.Uri". Error: "Invalid
URI: The hostname could not be parsed."
    + CategoryInfo          : InvalidArgument: (:) [New-PSSession], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.NewPSSessionCommand
    + PSComputerName        : localhost

Get-IpmSubtree job finished.
Cannot bind parameter 'ConnectionUri'. Cannot convert value "http:///powershell" to type "System.Uri". Error: "Invalid
URI: The hostname could not be parsed."
    + CategoryInfo          : InvalidArgument: (:) [New-PSSession], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.NewPSSessionCommand
    + PSComputerName        : localhost

Get-NonIpmSubtree job finished.
Cannot bind parameter 'ConnectionUri'. Cannot convert value "http:///powershell" to type "System.Uri". Error: "Invalid
URI: The hostname could not be parsed."
    + CategoryInfo          : InvalidArgument: (:) [New-PSSession], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.NewPSSessionCommand
    + PSComputerName        : localhost

The term 'Get-PublicFolderStatistics' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-PublicFolderStatistics:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost

Get-Statistics job finished.

Liked the script or had a problem? Let us know at ExToolsFeedback@microsoft.com
ForEach-Object : Index operation failed; the array index evaluated to null.
At C:\PFScripts\SourceSideValidations.ps1:1791 char:34
+ ... pmSubtree | ForEach-Object { $folderData.ParentEntryIdCounts[$_.Paren ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex,Microsoft.PowerShell.Commands.ForEachObjectCommand

**Comment by bill-long** [comment] 2024-01-29 16:59
This might be due to serialization signing. Were you running this from Exchange Management Shell on an Exchange server? It can't be a tools box - it must actually have the Mailbox role installed.

If that's not the cause, you can test this command in Exchange Management Shell (on the server):

$serverName = (Get-MailboxDatabase (Get-Mailbox -PublicFolder (Get-OrganizationConfig).RootPublicFolderMailbox.HierarchyMailboxGuid.ToString()).Database).Server.Name

This is how we get the name of the server that contains the hierarchy mailbox. If any part of this doesn't return a value, it will fail with the errors you saw. This currently fails in Remote PowerShell due to the serialization signing changes in the Nov SU.

If your issue is the serialization signing issue, it will be fixed when #1924 is merged. Maybe we can get that done today.

**Comment by bill-long** [comment] 2024-01-29 21:19
The #1924 fix is released, so if that was the problem, it was fixed in today's release (which is dated 24.01.16 because that's when the change was committed).

**Comment by copsec00** [comment] 2024-01-29 23:50
Prefect thank you for your response. I'll try the update.

**Closed** 2024-12-18 19:34 UTC
Labels: Public Folders, Issue
