### ISSUE TITLE
[Issue] - Health Checker shows sec vuln when disabling external access ECP

### ISSUE THREAD

**Issue by worldsdream** [microsoft/CSS-Exchange#1283] opened 2022-10-09 11:26 UTC
**Provide Version Number**
22.10.07.2032

**Describe the issue**
1. Disabled external access on ECP (https://www.alitajran.com/disable-external-access-to-ecp-exchange/).
2. Run the Health Checker
3. Health Checker shows below security vuln:

![OpxmnahHbi](https://user-images.githubusercontent.com/12443285/194754091-f6191c06-0f12-43a4-94b5-7d579ac0d30b.png)

**Expected behavior**
It's not telling clearly if we need to set something or if we should not use IP restrictions on ECP.

Shouldn't it be possible to use IP restrictions and get a NON-security vuln shown in Health Checker? Or another piece of information that tells us what to do so this can be fixed.

**Comment by dpaulson45** [comment] 2022-10-10 13:51
duplicate of #1260

**Closed** 2022-10-17 23:11 UTC
Labels: duplicate, Issue, Health Checker
