### ISSUE TITLE
Fails to run on Exchange 2010

### ISSUE THREAD

**Issue by rish501** [microsoft/CSS-Exchange#177] opened 2021-03-09 12:51 UTC
I have tested on two separate instances of Exchange 2010 SP3 (both Windows 2008R2). Same Error:

```
Unable to find type [pscredential]: make sure that the assembly containing this type is loaded.
At \Downloads\Test-ProxyLogon.ps1:85 char:27
+             [pscredential] <<<<
    + CategoryInfo          : InvalidOperation: (pscredential:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

**Comment by bill-long** [comment] 2021-03-09 12:53
Duplicate of #108 

Please see: https://github.com/microsoft/CSS-Exchange/issues/108#issuecomment-793045938

**Closed by bill-long** 2021-03-09 12:53 UTC
