### ISSUE TITLE
CompareExchangeHashes: baseline_15.0.995.28.zip not found

### ISSUE THREAD

**Issue by RUDI-TERROR** [microsoft/CSS-Exchange#353] opened 2021-03-15 14:18 UTC
Hey,

when we run the CompareExchangeHashes script we get a error message, that the file baseline_15.0.995.28.zip could not found:

```
PS C:\Users\adminst\Downloads> .\CompareExchangeHashes.ps1
[03/15/2021 14:48:43] Started...
Found exchange version: 15.0.1497.2
Can't find local baseline for 15.0.1497.2
Downloading baseline file from GitHub to C:\Users\adminst\Downloads\baseline_15.0.1497.2.zip
Loaded baseline for 15.0.1497.2, hashes number 7395
Can't find local baseline for 15.0.1497.12
Downloading baseline file from GitHub to C:\Users\adminst\Downloads\baseline_15.0.1497.12.zip
Loaded baseline for 15.0.1497.12, hashes number 7464
Can't find local baseline for 15.0.1473.3
Downloading baseline file from GitHub to C:\Users\adminst\Downloads\baseline_15.0.1473.3.zip
Loaded baseline for 15.0.1473.3, hashes number 7394
Can't find local baseline for 15.0.847.32
Downloading baseline file from GitHub to C:\Users\adminst\Downloads\baseline_15.0.847.32.zip
Loaded baseline for 15.0.847.32, hashes number 6825
Can't find local baseline for 15.0.995.32
Downloading baseline file from GitHub to C:\Users\adminst\Downloads\baseline_15.0.995.32.zip
Loaded baseline for 15.0.995.32, hashes number 11829
Can't find local baseline for 15.0.1365.1
Downloading baseline file from GitHub to C:\Users\adminst\Downloads\baseline_15.0.1365.1.zip
Loaded baseline for 15.0.1365.1, hashes number 7462
Can't find local baseline for 15.0.1497.0
Downloading baseline file from GitHub to C:\Users\adminst\Downloads\baseline_15.0.1497.0.zip
Loaded baseline for 15.0.1497.0, hashes number 7464
Can't find local baseline for 15.0.995.28
Downloading baseline file from GitHub to C:\Users\adminst\Downloads\baseline_15.0.995.28.zip
LoadFromGitHub : C:\Users\adminst\Downloads\baseline_15.0.995.28.zip not found... **please open issue on**
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\Users\adminst\Downloads\CompareExchangeHashes.ps1:660 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

```

**Comment by bill-long** [comment] 2021-03-15 14:36
Duplicate of #313 . This one is already on the list of missing baselines.

**Closed by bill-long** 2021-03-15 14:36 UTC
