### ISSUE TITLE
baseline_15.1.1531.10.zip not found

### ISSUE THREAD

**Issue by tomtummetott** [microsoft/CSS-Exchange#276] opened 2021-03-11 09:02 UTC
**Script Output**
```
[03/11/2021 10:00:47] Started...
Found exchange version: 15.1.2106.2
Can't find local baseline for 15.1.1531.10
Downloading baseline file from GitHub to C:\Windows\temp\compare\baseline_15.1.1531.10.zip
LoadFromGitHub : C:\Windows\temp\compare\baseline_15.1.1531.10.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
In C:\Windows\temp\compare\CompareExchangeHashes.ps1:647 Zeichen:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub
```

**Additional context**
```
ProductVersion   FileVersion      FileName
--------------   -----------      --------
15.01.2106.013   15.01.2106.013   D:\Exchange Server\V15\bin\ExSetup.exe
```
German version if it matters

Thanks and regards,
Andre

**Comment by MvanGroenigen** [comment] 2021-03-11 09:18
Last night the scripts and baselines where moved to a subdirectory /src/ on github
This breaks older versions, make sure you use the latest version of the script.

https://github.com/microsoft/CSS-Exchange/releases/latest/download/CompareExchangeHashes.ps1

**Comment by patrick131184** [comment] 2021-03-11 09:44
I have the same problem using latest CompareExchangeHashes.ps1.

baseline_15.1.1531.10.csv is not present in https://github.com/microsoft/CSS-Exchange/tree/main/Security/src/Baselines

**Comment by tomtummetott** [comment] 2021-03-11 10:02
I was using latest version. Downloaded 2 hours ago

```
Version 21.03.11.0620
```

**Comment by jupsoleil** [comment] 2021-03-11 11:15
Same version, same problem. 
Actually, I wonder why it doesn't search for the baseline for the exchange version (baseline_15.1.2176.2.csv is present in src):
Found exchange version: 15.1.2106.2
Can't find local baseline for 15.1.1531.10

**Comment by Masterkey1979** [comment] 2021-03-11 11:47
same here

[PS] C:\tmp>.\CompareExchangeHashes.ps1
[03/11/2021 12:33:29] Started...
Found exchange version: 15.1.2106.2
Can't find local baseline for 15.1.1531.10
Downloading baseline file from GitHub to C:\tmp\baseline_15.1.1531.10.zip
LoadFromGitHub : C:\tmp\baseline_15.1.1531.10.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
In C:\tmp\CompareExchangeHashes.ps1:647 Zeichen:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -in ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by SchmatzS** [comment] 2021-03-11 12:41
I have the same issue with the newest script:
https://github.com/microsoft/CSS-Exchange/releases/latest/download/CompareExchangeHashes.ps1

**Comment by bill-long** [comment] 2021-03-11 13:45
We don't have 15.1.15310.10 baseline available yet. Closing this as a duplicate of #258 .

**Closed by bill-long** 2021-03-11 13:45 UTC
Labels: Issue
