### ISSUE TITLE
[Issue] Exchange Healthchecker: Exchange Server Membership: Unknown

### ISSUE THREAD

**Issue by wachtell** [microsoft/CSS-Exchange#2221] opened 2024-11-10 15:28 UTC
**Describe the issue**
I run Exchange Healthchecker every day. However, I get a yellow error regarding Exchange Server membership. The error is not consistent and can be on one or more Exchange Servers.

**Script Output**
Exchange Server Membership: Unknown - Wasn't able to get the Computer Membership information

**Additional context**
Everything works correctly, and the event log has no real errors. Is this important or can I disregard the error?

Thank you in advance
Kris

**Comment by dpaulson45** [comment] 2024-11-22 19:56
duplicate of #2110

**Comment by dpaulson45** [comment] 2024-12-11 13:33
Closing, as this issue should be resolved with the PR #2229

**Closed by dpaulson45** 2024-12-11 13:33 UTC
Labels: duplicate, Issue, Health Checker, P0
