### ISSUE TITLE
baseline_15.0.516.30.zip not found

### ISSUE THREAD

**Issue by InfuseTechDerby** [microsoft/CSS-Exchange#280] opened 2021-03-11 10:19 UTC
Downloading baseline file from GitHub to C:\Infuse\baseline_15.0.516.30.zip
LoadFromGitHub : C:\Infuse\baseline_15.0.516.30.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\Infuse\CompareExchangeHashes.ps1:647 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

Running the CompareExchangeHashes.ps1 script

**Comment by bill-long** [comment] 2021-03-11 14:28
Duplicate of #279 ... You both opened an issue at almost the same time. :)

**Closed by bill-long** 2021-03-11 14:28 UTC
Labels: Issue
