### ISSUE TITLE
[Issue]Test-ProxyLogon.ps1 Exchange 2010

### ISSUE THREAD

**Issue by greenstreak20** [microsoft/CSS-Exchange#144] opened 2021-03-08 15:00 UTC
The provided script fails. Following is the output. How can I resolved the issue?

[PS] C:\Windows\system32>Get-ExchangeServer | ".\Test-ProxyLogon.ps1" -OutPath $home\desktop\logs
You must provide a value expression on the right-hand side of the '-' operator.
At line:1 char:47
+ Get-ExchangeServer | ".\Test-ProxyLogon.ps1" - <<<< OutPath $home\desktop\logs
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedValueExpression

**Comment by bill-long** [comment] 2021-03-08 16:01
I don't see any problem with the syntax. Did invisible characters sneak in? I would try typing it out by hand rather than copy/pasting.

**Comment by greenstreak20** [comment] 2021-03-08 16:06
I’ll give it a try and let you know.

Thanks.

[http://vm-shrpntprod/signaturecreator/greenline.png]
Wesley T. Hinkle, ITIL
Network Infrastructure Manager
Sterne, Kessler, Goldstein & Fox P.L.L.C.<http://www.sternekessler.com/>
Email: whinkle@sternekessler.com<mailto:whinkle@sternekessler.com>
Direct: 202.772.8917   Main: 202.371.2600

**Comment by greenstreak20** [comment] 2021-03-08 16:26
Bill,

Typing as opposed to c/p helped, but I get the following output. Forgive the questions, PS is not my normal job and the associated team is not responding, but I need to get his calidate.

Thanks

[PS] C:\Install\Exchange Vul 3-21>Get-ExchangeServer | .\Test-ProxyLogon.ps1 -OutPath $HOME\desktop\logs
Unable to find type [pscredential]: make sure that the assembly containing this type is loaded.
At C:\Install\Exchange Vul 3-21\Test-ProxyLogon.ps1:84 char:27
+             [pscredential] <<<<
    + CategoryInfo          : InvalidOperation: (pscredential:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

[http://vm-shrpntprod/signaturecreator/greenline.png]
Wesley T. Hinkle, ITIL
Network Infrastructure Manager
Sterne, Kessler, Goldstein & Fox P.L.L.C.<http://www.sternekessler.com/>
Email: whinkle@sternekessler.com<mailto:whinkle@sternekessler.com>
Direct: 202.772.8917   Main: 202.371.2600

**Comment by jakewalkeruct** [comment] 2021-03-08 17:42
I am receiving the same error as above when trying to run the script on Exch 2010.  Running Exch Mgmt Shell as admin.

Unable to find type [pscredential]: make sure that the assembly containing this type is loaded.
At C:\Users\jake.walker.da\Desktop\HAFNIUM Test Scipts\Test-ProxyLogon.ps1:84 char:27
+             [pscredential] <<<<
    + CategoryInfo          : InvalidOperation: (pscredential:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by bill-long** [comment] 2021-03-08 17:43
For the pscredential error please see #108

**Comment by bill-long** [comment] 2021-03-08 17:44
This has turned into a duplicate of #108 so closing it.

**Closed by bill-long** 2021-03-08 17:44 UTC
Labels: Issue

**Comment by greenstreak20** [comment] 2021-03-08 18:02
Thanks!

[http://vm-shrpntprod/signaturecreator/greenline.png]
Wesley T. Hinkle, ITIL
Network Infrastructure Manager
Sterne, Kessler, Goldstein & Fox P.L.L.C.<http://www.sternekessler.com/>
Email: whinkle@sternekessler.com<mailto:whinkle@sternekessler.com>
Direct: 202.772.8917   Main: 202.371.2600
