### ISSUE TITLE
[Issue] Can't find local baseline for 15.1.1531.10

### ISSUE THREAD

**Issue by adelsaut** [microsoft/CSS-Exchange#290] opened 2021-03-11 14:56 UTC
**Describe the issue**
This error display while trying to use .\CompareExchangeHashes.ps1 script to check Exchange Health. 

**Script Output**
If applicable, add the exception that you are seeing that wasn't handled.
PS C:\Users\FME\Downloads> .\CompareExchangeHashes.ps1

Do you want to run software from this untrusted publisher?
File C:\Users\FME\Downloads\CompareExchangeHashes.ps1 is published by CN=Microsoft Corporation, O=Microsoft
Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): R
[03/11/2021 15:44:01] Started...
Found exchange version: 15.1.2176.2
Can't find local baseline for 15.1.1531.10
Downloading baseline file from GitHub to C:\Users\FME\Downloads\baseline_15.1.1531.10.zip
LoadFromGitHub : C:\Users\FME\Downloads\baseline_15.1.1531.10.zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\Users\FME\Downloads\CompareExchangeHashes.ps1:647 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -in ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

PS C:\Users\FME\Downloads>

Thanks for the help. ;-)

**Comment by Wittionary** [comment] 2021-03-11 16:37
I'm experiencing this issue as well. When I go to the releases page, there's no baseline for "15.1.1531.10".

**Comment by bill-long** [comment] 2021-03-11 16:53
Duplicate of #258

**Closed by bill-long** 2021-03-11 16:53 UTC
Labels: Issue
