### ISSUE TITLE
Exchange Baseline 15.0.516.30 zip not found

### ISSUE THREAD

**Issue by pperez8707** [microsoft/CSS-Exchange#360] opened 2021-03-15 22:38 UTC
Support,

I ran the Exchange mitigation tool on my on-prem exchange server and I got the error that the Exchange Baseline 15.0.516.30 zip not found. The error states to open a ticket for the baseline required for my Exchange server. My on-prem Exchange server is 2013 CU23.

**Comment by bill-long** [comment] 2021-03-15 22:44
Duplicate of #313

**Closed by bill-long** 2021-03-15 22:44 UTC
