### ISSUE TITLE
Missing baseline_15.1.1713.9

### ISSUE THREAD

**Issue by marioneubert** [microsoft/CSS-Exchange#329] opened 2021-03-12 13:12 UTC
**Describe the issue**
The script reports me many .js files in directory "ClientAccess\Owa\prem\15.1.1713.9\". I can not see a basefile for this version in the repository and there is no entry as valid version for E16 in the script. Seems for me to be a false positive. Creation Date of the files is the time and date when we installed Security Update For Exchange Server 2016 Cumulative Update 12 (KB4515832)

**Expected behavior**
Base files for all exchange version and fixes
or
if it makes sense just scan the current version

**Comment by michaelweigele** [comment] 2021-03-12 17:16
The same applies to "ClientAccess\Owa\prem\15.1.1713.6" (KB4487563), "ClientAccess\Owa\prem\15.1.1713.7" (KB4503027) and "ClientAccess\Owa\prem\15.1.1713.8" (KB4509409)

**Comment by psykokwak4** [comment] 2021-03-13 00:51
should be fixed with recent releases, please retry with latest script (https://github.com/microsoft/CSS-Exchange/releases/download/v21.03.12.2223/CompareExchangeHashes.ps1)

also, if the missing *js files are localized files (e.g. *Strings.localized.min.js), then it is caused by the fact that we did not collect baseline data for localized files, please follow `#313` for baseline updates

**Comment by psykokwak4** [comment] 2021-03-13 00:51
#313

**Closed by psykokwak4** 2021-03-13 00:51 UTC
Labels: Issue

**Comment by michaelweigele** [comment] 2021-03-14 01:21
The baseline for 15.1.1713.6 still missing
