### ISSUE TITLE
[Question] CompareExchangeHashes.ps1 finds more than 50000 Errors?

### ISSUE THREAD

**Issue by mi271** [microsoft/CSS-Exchange#350] opened 2021-03-15 10:23 UTC
Running CompareExchangeHashes.ps1 shows me more than 50000 times "NoHashMatch"
Since Baseline 15.0.516.30 is still missing i commented this part out in the script.
Exchange 2013 CU23, fully patched. No other signs of Hafnium attacks found

**Comment by mi271** [comment] 2021-03-15 10:33
`

07/10/2013 07:42:43,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:19:28","NoHashMatch","D2C5092127D53369E249644924AB45D648C20E4DCF5D099EDEDD4A6B5014D967","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\cs\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:19:28","Exchange Back End/owa/"
--
07/10/2013   07:42:45,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:19:38","NoHashMatch","2467797084B16A1F7CE3C1EFD2A10B7F2AB11B825EFAB17C98992A5752A3086E","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\de\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:19:38","Exchange Back End/owa/"
07/10/2013   07:42:51,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:20:02","NoHashMatch","FDA97C8CB1AD4FB0085D3756A0924EC3A31D1C391E2DD3754379ACD8265D19B7","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\es\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:20:02","Exchange Back End/owa/"
07/10/2013   07:42:58,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:20:22","NoHashMatch","FEEF5652349DC206A3351275C92D2D4EF90611695A3F58A1F5EA9432F7C61CD4","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\fr\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:20:22","Exchange Back End/owa/"
07/10/2013   07:43:03,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:20:36","NoHashMatch","F95FDA8AF6BC852AAF4D0D8261B53AC33543A287C276E855351D26B7835AC629","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\hi\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:20:36","Exchange Back End/owa/"
07/10/2013   07:43:07,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:20:50","NoHashMatch","77B69E57CA67E8F747CA9C9970B11EE81F7B1569F3E8369045948E7143392108","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\it\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:20:50","Exchange Back End/owa/"
07/10/2013   07:43:09,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:00","NoHashMatch","A14D4DB062CCB9D2A7407AAB09108F6521F3C9F1D40E4344A3D1F8218206352F","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\ja\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:00","Exchange Back End/owa/"
07/10/2013   07:43:12,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:14","NoHashMatch","809A07D38260C27E74E10CB760686FA1BB81D5A323ED9395FE304172B610B3C1","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\ko\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:14","Exchange Back End/owa/"
07/10/2013   07:43:15,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:22","NoHashMatch","1A9638A1151A5E25877C62BE6F93850C4718E1F0743C3F045C39E0F39581CBC9","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\lv\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:22","Exchange Back End/owa/"
07/10/2013   07:43:15,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:24","NoHashMatch","73FEEC8D12CAC2793FBE91FAC917CD7CAD36095AC37EB755688A1DECD0A5FCDF","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\ml\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:24","Exchange Back End/owa/"
07/10/2013   07:43:17,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:28","NoHashMatch","33A3D31DA4D8B9686FAC69F5504E812CDDC340467141C4334C8CCE71067257A3","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\ms\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:28","Exchange Back End/owa/"
07/10/2013   07:43:21,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:36","NoHashMatch","F4C5BEA566DA0A6C5A84CD1A21053BE77B10C70F5DEFBE5D0B2837D5D4D4E541","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\no\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:36","Exchange Back End/owa/"
07/10/2013   07:43:25,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:46","NoHashMatch","2757CB41A01BED0C0FE39D4CD44DCB207B487F1F33847A92EE6B17C6F265AA44","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\pt\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:21:46","Exchange Back End/owa/"
07/10/2013   07:43:31,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:22:00","NoHashMatch","350A4740C2F386DBF1A57C834C88028C7E22910BB3D98C753CC18AE42D786E9B","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\ru\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:22:00","Exchange Back End/owa/"
07/10/2013   07:43:35,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:24:24","NoHashMatch","AF8D8085ACB82760E0247BF886F6A5447E4D421A3386D7F4597AEAD216509116","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\sk\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:24:24","Exchange Back End/owa/"
07/10/2013   07:43:41,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:24:38","NoHashMatch","3912F7212D86B8530B657C51BF8EF4E1E6502445E27B26A7D5FDEAFA2233462E","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\ta\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:24:38","Exchange Back End/owa/"
07/10/2013   07:43:46,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:24:56","NoHashMatch","F291D5E6A72175EC331BC07902CE70CCFA14DD3C9460BB24FD4D1FD970DBD24F","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\zh-hans\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:24:56","Exchange Back End/owa/"
07/10/2013   07:43:49,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:25:04","NoHashMatch","C37FEACAE110F3C28310214B927B1B2D29D4B85248013B6070ACF2D0F9EF7C12","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\ext\def\zh-hant\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.min.js","03/29/2013   02:25:04","Exchange Back End/owa/"
07/10/2013   07:42:39,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.OOBEStrings.Localized.min.js","03/29/2013   02:19:14","NoHashMatch","CE0C32447F241165E82AA0D8565EA9B9861C9D15E79F7775503814882AC1693F","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\scripts\am\Microsoft.Exchange.Clients.Owa2.Client.OOBEStrings.Localized.min.js","03/29/2013   02:19:14","Exchange Back End/owa/"
07/10/2013   07:42:39,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.Strings.Localized.min.js","03/29/2013   02:19:14","NoHashMatch","4F195EE31C119CBF457F6958001A79AB44C48E64E7AF6DEC346D77FF3E6D7692","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\scripts\am\Microsoft.Exchange.Clients.Owa2.Client.Strings.Localized.min.js","03/29/2013   02:19:14","Exchange Back End/owa/"
07/10/2013   07:42:40,"C:\Program Files\Microsoft\Exchange   Server\V15\ClientAccess\owa","Microsoft.Exchange.Clients.Owa2.Client.OOBEStrings.Localized.min.js","03/29/2013   02:19:18","NoHashMatch","10901C542645C2FA28CCF3D94F6D84E37B544D4DCF226650FA416EC7172243EA","C:\Program   Files\Microsoft\Exchange   Server\V15\ClientAccess\owa\15.0.620.29\Owa2\scripts\ar\Microsoft.Exchange.Clients.Owa2.Client.OOBEStrings.Localized.min.js","03/29/2013   02:19:18","Exchange Back End/owa/"

`

**Comment by ChrisNbg** [comment] 2021-03-15 11:45
I have the same problem here although with EX2013 CU23 and all patches...

Script is missing Baselines for 15.0.712.23 and 15.0.516.30... tried to disable them in the script with "false". Then the scripts is running and has over 13.000 entries in the result.csv

**Comment by bill-long** [comment] 2021-03-15 16:21
Looks like a duplicate of #313 . 15.0.516.30 and 15.0.712.23 are already in the list.

**Closed by bill-long** 2021-03-15 16:21 UTC
