### ISSUE TITLE
[Work Item] NodeRunner Memory check on HealthChecker

### ISSUE THREAD

**Issue by johage** [microsoft/CSS-Exchange#1686] opened 2023-05-03 15:39 UTC
**Describe the work**
Using build 23.05.02.2057 we don't appear to have any checks for the noderunner.exe.config located here - C:\Program Files\Microsoft\Exchange Server\V15\Bin\Search\Ceres\Runtime\1.0 to validate the value for "nodeRunnerSettings memoryLimitMegabytes"

**Additional Context**
**// Default configuration**
  
  
  **<nodeRunnerSettings memoryLimitMegabytes="0"/>**

**// Adjusted configuration**
  
  
  **<nodeRunnerSettings memoryLimitMegabytes="1024"/>**

**Comment by dpaulson45** [comment] 2023-05-05 15:04
Duplicate of #927

**Closed** 2024-01-29 14:20 UTC
Labels: duplicate, Work Item, Health Checker
