### ISSUE TITLE
[Issue] - Health Checker - feature request - UnifiedContent temp path check

### ISSUE THREAD

**Issue by githubths** [microsoft/CSS-Exchange#2067] opened 2024-04-22 14:36 UTC
Hi Exchange Team,

Please add the following additional check in the Script.

check whether the current UnifiedContent temp path of the Transport Configuration is also included as a cleanup path in Antimalware.xml in the CleanupFolderResponderFolderPaths section. If the path is not included, a warning should be issued. 

The current path used for the UnifiedContent directory can be read in the $env:ExchangeInstallPath\bin\EdgeTransport.exe.config file in the 'TemporaryStoragePath' section.

The whole thing is described in the Doc [article](https://learn.microsoft.com/en-us/exchange/troubleshoot/administration/unifiedcontent-folder-fills-up-drive) and is actually a misconfiguration that can lead to mailflow problems. 

Regards Steve

P.S : The Script that is described in the Doc Article at the end is not working correctly.

**Comment by dpaulson45** [comment] 2024-04-22 15:44
Duplicate of #1086

**Closed** 2024-08-08 15:22 UTC
Labels: duplicate, enhancement, Health Checker, New Feature/Check, P2, Work - Medium Change, HC - Add Data Collection

**Comment by dpaulson45** [comment] 2024-08-13 13:53
@sjaak327 please email in the Health Checker results. Please include the xml and txt file. ExToolsFeedback@microsoft.com

**Comment by sjaak327** [comment] 2024-08-13 14:03
I moved the transport db, and the TemporaryStoragePath" in edgetransport.exe.conrfig is set to a completely different value Not  $env:ExchangeInstallPath\TransportRoles\data\Temp\UnifiedContent I added the value there, re-ran the script, it is still complaining. Do I need to restart some services ?

**Comment by sjaak327** [comment] 2024-08-13 14:22
anyway, sending the results now. It is still complaining. Even after a complete reboot
